AI_INSIGHTS = {
    'insurance': {
        'default': [
            ('Insurance Policy', "What is the coverage agreement in the insurance policy?"),
            ('Insured', "Who is the person covered under the policy?"),
            ('Insurer', "Which company is the insurer for this policy?"),
            ('Premium', "What is the premium amount for this insurance?"),
            ('Claim', "How do I file a claim for a recent loss?"),
            ('Coverage', "What does the insurance coverage include?"),
            ('Sum Insured', "What is the sum insured for this policy?"),
            ('Deductible', "How much is the deductible on this policy?"),
            ('Co-Payment', "What is the co-payment required for a claim?"),
            ('Exclusions', "What are the exclusions in this policy?"),
            ('Riders', "Can I add riders to my current insurance policy?"),
            ('Renewal', "How do I renew my insurance policy?"),
            ('Lapse', "What happens if my policy lapses due to non-payment?"),
        ],
        'health': [
            ('Insurance Policy', "What does the insurance policy cover?"),
            ('Insured', "Who is the insured person under this policy?"),
            ('Insurer', "Which company is the insurer for this plan?"),
            ('Premium', "What is the premium cost for this insurance?"),
            ('Claim', "How do I file a claim for a loss?"),
            ('Coverage', "What type of coverage does this policy provide?"),
            ('Sum Insured', "What is the sum insured for this insurance?"),
            ('Deductible', "How much is the deductible on this policy?"),
            ('Co-Payment', "What is the co-payment required for this claim?"),
            ('Exclusions', "What exclusions apply to this policy?"),
            ('Riders', "Can I add riders to enhance my coverage?"),
            ('Renewal', "How do I renew my insurance policy?"),
            ('Lapse', "What happens if my policy lapses due to non-payment?"),
            ('Individual Health Insurance', "Does this policy offer individual health insurance coverage?"),
            ('Family Floater Health Insurance', "What is covered under a family floater health insurance plan?"),
            ('Cashless Treatment', "How does cashless treatment work?"),
            ('Reimbursement', "How can I get reimbursement after hospitalization?"),
            ('Pre-Existing Conditions', "Are pre-existing conditions covered under this policy?"),
            ('Waiting Period', "What is the waiting period before coverage starts?"),
            ('Health Check-ups', "Are health check-ups covered under this insurance?"),
            ('In-Patient Treatment', "Does this policy cover in-patient treatment?"),
            ('Out-Patient Treatment', "What is covered under out-patient treatment?"),
            ('Daycare Treatment', "Are daycare treatments covered in this policy?"),
            ('Domiciliary Hospitalization', "Is domiciliary hospitalization included in this plan?"),
            ('Ambulance Charges', "Does this policy cover ambulance charges?"),
            ('Pre-Hospitalization Expenses', "Are pre-hospitalization expenses reimbursed?"),
            ('Post-Hospitalization Expenses', "Does the policy cover post-hospitalization expenses?"),
            ('Organ Transplant Coverage', "Is organ transplant coverage included in this plan?"),
            ('Maternity Benefit', "What is the maternity benefit under this policy?"),
            ('Newborn Baby Coverage', "Does this policy cover a newborn baby?"),
            ('Policyholder', "Who is the policyholder of this insurance?"),
            ('Nominee', "Who is the nominee for this insurance policy?"),
            ('Claim Settlement', "How does the claim settlement process work?"),
            ('Surrender Value', "What is the surrender value of my policy?"),
            ('Tax Benefits', "What tax benefits are available with this insurance?"),
            ('IRDA (Insurance Regulatory and Development Authority)', "How does IRDA regulate insurance in India?"),
        ],
        'auto': [
            ('Insurance Policy', "Where can I find the official insurance policy document?"),
            ('Sum', "What is the maximum sum insured for this policy?"),
            ('Premium', "How often do I need to pay the premium?"),
            ('Coverage', "What types of losses are covered under this insurance?"),
            ('Deductible', "What is the deductible amount for this policy?"),
            ('Exclusions', "What exclusions are listed in the policy?"),
            ('Riders', "Can I add riders to my current insurance coverage?"),
            ('Third-Party', "Does this policy cover third-party liability?"),
            ('Own', "What is included under own damage coverage for my vehicle?"),
            ('Comprehensive', "What does comprehensive coverage protect against?"),
            ('Personal', "Does this policy include personal accident coverage?"),
            ('No', "How does the No Claim Bonus (NCB) work?"),
            ('Zero', "Is zero depreciation coverage available for my vehicle?"),
            ('Engine', "Does the policy include engine protect coverage?"),
            ('Return', "How does the return to invoice cover work?"),
            ('Add-on', "What add-on covers are available with this auto insurance?"),
            ('Policyholder', "Who is the policyholder for this insurance policy?"),
            ('Nominee', "Who is the nominee listed in this policy?"),
            ('Claim', "What is the claim settlement process?"),
            ('Surrender', "What is the surrender value of my policy?"),
            ('Tax', "Are there any tax benefits associated with this insurance?"),
            ('IRDA', "How does the IRDA regulate insurance policies in India?"),
            ('Incontestability', "What is the incontestability clause in this insurance policy?"),
            ('Proposer', "Who is the proposer of this insurance policy?"),
            ('Claim', "Where can I obtain a claim form?"),
            ('Policy', "What details are included in the policy document?"),
            ('Renewal', "When will I receive the renewal notice for my policy?"),
        ],
        'life': [
            ('Insurance Policy', "Where can I find my insurance policy document?"),
            ('Sum', "What is the sum insured in this policy?"),
            ('Premium', "How often is the premium payment due?"),
            ('Coverage', "What types of losses are covered under this insurance?"),
            ('Deductible', "What is the deductible I need to pay before the insurer steps in?"),
            ('Exclusions', "What exclusions are there in this policy?"),
            ('Riders', "Can I add riders to my existing insurance coverage?"),
            ('Term', "What is the term length of this life insurance policy?"),
            ('Death', "What is the death benefit amount for this policy?"),
            ('Accidental', "Does this policy include an accidental death benefit?"),
            ('Critical', "Is there a critical illness benefit in this policy?"),
            ('Waiver', "Will the premium be waived if I become disabled?"),
            ('Return', "How does the return of premium feature work?"),
            ('Policyholder', "Who is the policyholder of this insurance?"),
            ('Nominee', "Who is the nominee listed in this policy?"),
            ('Claim', "What is the process for claim settlement?"),
            ('Surrender', "What is the surrender value of my policy?"),
            ('Tax', "What are the tax benefits associated with this policy?"),
            ('IRDA', "What role does the IRDA play in insurance regulation?"),
            ('Incontestability', "What is the incontestability clause in this policy?"),
            ('Proposer', "Who is the proposer of this insurance?"),
            ('Claim', "Where can I get a claim form?"),
            ('Policy', "What details are included in the policy document?"),
            ('Renewal', "When will I receive a renewal notice for my policy?"),
        ],
        'homeowners': [
            ('Insurance Policy', "Where can I access the official insurance policy document?"),
            ('Sum', "What is the sum insured under this policy?"),
            ('Premium', "How much is the premium for this insurance?"),
            ('Coverage', "What types of losses are covered in this policy?"),
            ('Deductible', "What is the deductible amount I need to pay?"),
            ('Exclusions', "What exclusions are included in this insurance policy?"),
            ('Riders', "Can I add riders for additional coverage options?"),
            ('Building', "What does the building coverage include in my home insurance?"),
            ('Contents', "Does this policy cover the contents inside my home?"),
            ('Additional', "Are additional living expenses covered if my home becomes uninhabitable?"),
            ('Liability', "What does liability coverage protect me against?"),
            ('Personal', "How does the personal property replacement cost work?"),
            ('Flood', "Does this policy include flood coverage?"),
            ('Earthquake', "Is earthquake coverage available under this insurance?"),
            ('Burglary', "Does this policy cover burglary or theft losses?"),
            ('Policyholder', "Who is the policyholder of this insurance policy?"),
            ('Nominee', "Who is the nominee in this insurance policy?"),
            ('Claim', "What is the process for claim settlement under this policy?"),
            ('Surrender', "What is the surrender value if I cancel the policy before maturity?"),
            ('Tax', "Are there any tax benefits associated with this policy?"),
            ('IRDA', "How does the IRDA regulate insurance policies in India?"),
            ('Incontestability', "What does the incontestability clause mean in this insurance?"),
            ('Proposer', "Who is the proposer of this insurance policy?"),
            ('Claim', "Where can I obtain a claim form for this insurance?"),
            ('Policy', "What key details are included in the policy document?"),
            ('Renewal', "When will I receive a renewal notice for my insurance policy?"),
        ],
        'travel': [
            ('Insurance', "Where can I access the insurance policy document?"),
            ('Sum', "What is the sum insured under this policy?"),
            ('Premium', "How often is the premium payment due?"),
            ('Coverage', "What types of losses are covered by this policy?"),
            ('Deductible', "What is the deductible amount I need to pay?"),
            ('Exclusions', "What are the exclusions in this insurance policy?"),
            ('Riders', "Can I add any riders for extra coverage?"),
            ('Medical', "Does this policy cover medical expenses during travel?"),
            ('Emergency', "Is emergency evacuation included in this travel insurance?"),
            ('Trip', "What is covered under trip cancellation?"),
            ('Trip', "How does trip interruption coverage work?"),
            ('Lost', "Does this policy cover lost or stolen baggage?"),
            ('Personal', "What is included in personal accident coverage?"),
            ('Hijacking', "Are hijacking and terrorism covered by this insurance?"),
            ('Pre-existing', "Are pre-existing conditions covered under this policy?"),
            ('Waiting', "What is the waiting period for certain coverage?"),
            ('Policyholder', "Who is the policyholder of this insurance policy?"),
            ('Nominee', "Who is the nominee for this insurance policy?"),
            ('Claim', "What is the claim settlement process for this policy?"),
            ('Surrender', "What is the surrender value if I cancel the policy early?"),
            ('Tax', "Are there any tax benefits associated with this insurance policy?"),
            ('IRDA', "How does the IRDA regulate insurance policies in India?"),
            ('Incontestability', "What does the incontestability clause mean in this policy?"),
            ('Proposer', "Who is considered the proposer of this insurance?"),
            ('Claim', "Where can I find a claim form for this policy?"),
            ('Policy', "What details are included in the policy document?"),
            ('Renewal', "When will I receive a renewal notice for my insurance policy?"),
        ],
    },
    'loan': {
        'default': [
            ('Principal Amount', "What is Principal Amount on this loan?"),
            ('Interest Rate', "What is the interest rate or APR for this loan?"),
            ('Tenure', "What is the tenure or duration of the loan?"),
            ('EMI (Equated Monthly Installment)', "How much is the EMI for this loan?"),
            ('Repayment Schedule', "What does the repayment schedule look like?"),
            ('Prepayment Penalty', "Is there a prepayment penalty for early repayment?"),
            ('Late Payment Penalty', "What is the late payment penalty if I miss a payment?"),
            ('Grace Period', "How long is the grace period for this loan?"),
            ('Moratorium Period', "What is the moratorium period for the loan?"),
            ('Interest-Only Payments', "Are interest-only payments an option?"),
            ('Fixed/Variable Interest Rate', "Is the interest rate fixed or variable?"),
            ('Loan Agreement', "What are the key terms in the loan agreement?"),
            ('Offer Letter', "What does the offer letter include?"),
            ('Sanction Letter', "What details are in the sanction letter?"),
            ('Disbursement Schedule', "What is the disbursement schedule for the loan?"),
            ('Loan Statement', "How can I get a loan statement?"),
            ('Loan Closure Certificate', "How do I obtain a loan closure certificate?"),
            ('Collateral', "What collateral is required for this loan?"),
            ('Guarantor', "Who is a guarantor for this loan?"),
            ('Credit Score', "How does my credit score affect the loan?"),
            ('Eligibility Criteria', "What are the eligibility criteria for this loan?"),
            ('Required Documents', "What documents are required to apply for the loan?"),
            ('Approval Turnaround', "What is the approval turnaround time for this loan?"),
            ('Loan Transfer', "Can I transfer my loan to another lender?"),
            ('Loan Refinancing', "How does loan refinancing work?"),
            ('Tax Benefits', "Are there any tax benefits associated with this loan?"),
            ('Loan Insurance', "Is loan insurance available for this loan?"),
            ('Loan Default', "What happens if I default on the loan?"),
            ('Dispute Resolution', "How are disputes or complaints resolved?"),
            ('Processing Fees', "What are the processing fees for the loan?"),
            ('Hidden Charges', "Are there any hidden charges with this loan?"),
            ('Part Payment', "Can I make part payments on this loan?"),
            ('Maximum Loan Amount', "What is the maximum loan amount I can borrow?"),
            ('Loan Tracking', "How can I track the status of my loan?"),
            ('Automatic Deduction', "Is automatic deduction available for EMI payments?"),
            ('Balance Transfer', "Can I transfer my loan balance to another lender?"),
        ],
        'home': [
            ('Principal Amount', "What is Principal Amount on this loan?"),
            ('Interest Rate', "What is the interest rate or APR for this home loan?"),
            ('Tenure', "What is the tenure or duration of the home loan?"),
            ('EMI (Equated Monthly Installment)', "How much is the EMI for this home loan?"),
            ('Repayment Schedule', "What does the repayment schedule look like for this loan?"),
            ('Prepayment Penalty', "Is there a prepayment penalty if I repay the loan early?"),
            ('Late Payment Penalty', "What is the late payment penalty for missed payments?"),
            ('Grace Period', "How long is the grace period for this loan?"),
            ('Moratorium Period', "Is there a moratorium period available?"),
            ('Interest-Only Payments', "Are interest-only payments an option for this loan?"),
            ('Fixed/Variable Interest Rate', "Is the interest rate fixed or variable?"),
            ('Loan-to-Value (LTV) Ratio', "What is the Loan-to-Value (LTV) ratio for this home loan?"),
            ('Stamp Duty', "What is the stamp duty for this property?"),
            ('Registration Charges', "What are the registration charges for the property?"),
            ('Processing Fees', "What are the processing fees for this loan application?"),
            ('Legal Fees', "What legal fees are associated with this loan?"),
            ('Valuation Charges', "What are the valuation charges for assessing the property's value?"),
            ('No Objection Certificate (NOC)', "What is a No Objection Certificate (NOC) and do I need one?"),
            ('Home Insurance', "Is home insurance required for this loan?"),
            ('Property Tax', "What property tax will I need to pay?"),
            ('Home Loan Eligibility', "What are the criteria for home loan eligibility?"),
            ('Home Loan Approval', "How can I get approval for a home loan?"),
            ('Home Loan Disbursement', "What is the home loan disbursement process?"),
            ('Home Loan Foreclosure', "What happens in case of home loan foreclosure?"),
            ('Mortgage Deed', "What is a mortgage deed?"),
            ('Collateral Security', "How does collateral security work for this loan?"),
            ('Lien', "What is a lien and how does it affect the property?"),
            ('Equitable Mortgage', "What is an equitable mortgage?"),
            ('Hypothecation', "What is hypothecation and how does it differ from other types of mortgages?"),
            ('Possession Mortgage', "What is a possession mortgage?"),
            ('Subordination Agreement', "What is a subordination agreement?"),
            ('Redemption', "How can I redeem my home loan?"),
            ('Home Loan Transfer', "How do I transfer my home loan to another lender?"),
            ('Home Loan Refinancing', "What is home loan refinancing and how does it work?"),
            ('Home Loan Prepayment', "Can I prepay my home loan before its maturity?"),
            ('Home Loan EMI Calculator', "How can I use a home loan EMI calculator?"),
            ('Home Loan Interest Calculator', "How does a home loan interest calculator work?"),
            ('Home Loan Eligibility Calculator', "What is a home loan eligibility calculator and how do I use it?"),
            ('Interest Rate Adjustment', "Is there a clause for adjusting the interest rate after a certain period?"),
            ('Early Payoff Penalties', "Are there any penalties for paying off the early? What are they?"),
        ],
        'personal': [
            ('Loan Sanction Letter', "What information in this sanction letter included?"),
            ('Sanctioned Amount', "What is The approved loan amount ? or what is The Sanctioned Amount ?"),
            ('Interest Rate', "What is interest rate for this loan?"),
            ('Tenure', "What is tenure for this loan?"),
            ('Repayment Schedule', "What is Repayment Schedule for this loan?"),
            ('Disbursement Schedule', "What is disbursement Schedule for this loan?"),
            ('Credit Score', "How does my credit score impact my home loan interest rate?"),
            ('Eligibility Criteria', "What are the key eligibility criteria for a first-time homebuyer loan?"),
            ('Required Documents', "Can you provide a checklist of required documents for a mortgage application?"),
            ('Approval Turnaround', "What's the typical approval turnaround time for a home loan application?"),
            ('Loan Transfer', "What are the steps involved in transferring my existing home loan to a new lender?"),
            ('Loan Refinancing', "Under what circumstances should I consider refinancing my mortgage?"),
            ('Tax Benefits', "What tax benefits are available for homeowners with a mortgage?"),
            ('Loan Default', "What happens if I default on my home loan payments?"),
            ('Dispute Resolution', "How does the dispute resolution process work if I have issues with my mortgage lender?"),
            ('Processing Fees', "What processing fees are associated with this home loan application?"),
            ('Hidden Charges', "How can I identify and avoid hidden charges in my mortgage agreement?"),
            ('Part Payment', "Is there a limit on how much I can pay as a part payment on my home loan?"),
            ('Maximum Loan Amount', "How is the maximum loan amount determined for a mortgage application?"),
            ('Loan Tracking', "What tools are available for tracking my home loan account and payments?"),
            ('Automatic Deduction', "How do I set up automatic deduction for my monthly mortgage payments?"),
            ('Balance Transfer', "What are the potential benefits and drawbacks of a mortgage balance transfer?"),
        ],
        'education': [
            ('Loan Sanction Letter', "What details are included in the loan sanction letter?"),
            ('Sanctioned Amount', "What is the sanctioned amount for this loan?"),
            ('Interest Rate', "What is the interest rate for this loan?"),
            ('Tenure', "What is the tenure of the loan?"),
            ('Repayment Schedule', "What does the repayment schedule include?"),
            ('Disbursement Schedule', "What is the disbursement schedule for the loan?"),
            ('Moratorium Period', "What is the moratorium period for this education loan?"),
            ('Interest Subsidy', "Is there an interest subsidy available for this loan?"),
            ('Co-Applicant', "Who can be a co-applicant for the education loan?"),
            ('Collateral', "What collateral is required for this education loan?"),
            ('Guarantor', "Who can act as a guarantor for this loan?"),
            ('Credit Score', "How does my credit score impact the loan application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for this loan?"),
            ('Required Documents', "What documents are required to process the loan application?"),
            ('Approval Turnaround', "What is the approval turnaround time for the loan?"),
            ('Loan Transfer', "Can I transfer my loan to another lender?"),
            ('Loan Refinancing', "How does loan refinancing work?"),
            ('Tax Benefits', "Are there any tax benefits associated with this loan?"),
            ('Loan Default', "What happens if I default on the loan?"),
            ('Dispute Resolution', "How are disputes or disagreements resolved?"),
            ('Processing Fees', "What are the processing fees for the loan application?"),
            ('Hidden Charges', "Are there any hidden charges associated with the loan?"),
            ('Part Payment', "Can I make a part payment towards the loan?"),
            ('Maximum Loan Amount', "What is the maximum loan amount I can borrow?"),
            ('Loan Tracking', "How can I track the status of my loan?"),
            ('Automatic Deduction', "Is automatic deduction available for loan payments?"),
            ('Balance Transfer', "How does a balance transfer work for this loan?"),
        ],
        'microfinance': [
            ('Loan Sanction Letter', "What information is included in the loan sanction letter?"),
            ('Sanctioned Amount', "What is the sanctioned amount for this loan?"),
            ('Interest Rate', "What is the interest rate applied to this loan?"),
            ('Tenure', "What is the tenure or duration of the loan?"),
            ('Repayment Schedule', "What does the repayment schedule detail?"),
            ('Disbursement Schedule', "What is the disbursement schedule for the loan?"),
            ('Collateral-Free', "Are collateral-free loans available in microfinance?"),
            ('Group Lending', "How does group lending work in microfinance?"),
            ('Joint Liability', "What is joint liability in microfinance loans?"),
            ('Gradual Repayment', "What does gradual repayment mean for microfinance loans?"),
            ('Microcredit', "How is microcredit typically used?"),
            ('Credit Score', "How does my credit score affect my microfinance loan application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for a microfinance loan?"),
            ('Required Documents', "What documents are required for applying for a microfinance loan?"),
            ('Approval Turnaround', "What is the approval turnaround time for microfinance loans?"),
            ('Loan Default', "What happens if I default on a microfinance loan?"),
            ('Dispute Resolution', "How are disputes resolved in microfinance?"),
            ('Microfinance Institution (MFI)', "What is a Microfinance Institution (MFI)?"),
            ('Self-Help Groups (SHGs)', "What are Self-Help Groups (SHGs) and how do they work?"),
            ('Joint Liability Groups (JLGs)', "What are Joint Liability Groups (JLGs) and their purpose?"),
            ('Interest Rates', "How do interest rates on microfinance loans compare to traditional bank loans?"),
        ],
        'mortgage':[
            ('Loan Sanction Letter', "What information is included in the loan sanction letter?"),
            ('Sanctioned Amount', "What is the sanctioned amount for this loan?"),
            ('Interest Rate', "What is the interest rate for this loan?"),
            ('Tenure', "What is the tenure or duration of the loan?"),
            ('Repayment Schedule', "What details are covered in the repayment schedule?"),
            ('Disbursement Schedule', "What does the disbursement schedule entail?"),
            ('Loan-to-Value (LTV) Ratio', "What is the Loan-to-Value (LTV) ratio for this mortgage?"),
            ('Stamp Duty', "What is the stamp duty for the property?"),
            ('Registration Charges', "What are the registration charges for the property?"),
            ('Processing Fees', "What processing fees are associated with the loan?"),
            ('Legal Fees', "What legal fees will I incur for this loan?"),
            ('Valuation Charges', "What are the valuation charges for assessing the property's value?"),
            ('No Objection Certificate (NOC)', "What is a No Objection Certificate (NOC) and how do I obtain one?"),
            ('Home Insurance', "Is home insurance required for this mortgage?"),
            ('Property Tax', "What property tax will be applicable?"),
            ('Mortgage Deed', "What is a mortgage deed and what does it include?"),
            ('Collateral Security', "What is meant by collateral security in this loan?"),
            ('Lien', "What is a lien and how does it affect the property?"),
            ('Equitable Mortgage', "What is an equitable mortgage?"),
            ('Hypothecation', "How does hypothecation differ from other types of mortgages?"),
            ('Possession Mortgage', "What is a possession mortgage?"),
            ('Subordination Agreement', "What is a subordination agreement?"),
            ('Redemption', "What is redemption and how does it work?"),
            ('Credit Score', "How does my credit score impact my mortgage application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for this mortgage loan?"),
            ('Required Documents', "What documents are needed to apply for the mortgage?"),
            ('Approval Turnaround', "What is the approval turnaround time for this mortgage loan?"),
            ('Loan Transfer', "Can I transfer my loan to another lender?"),
            ('Loan Refinancing', "What are the terms for loan refinancing?"),
            ('Tax Benefits', "Are there any tax benefits associated with this mortgage?"),
            ('Loan Default', "What happens if I default on the mortgage?"),
            ('Dispute Resolution', "How are disputes or disagreements resolved?"),
            ('Processing Fees', "What are the processing fees for the mortgage application?"),
            ('Hidden Charges', "Are there any hidden charges associated with this mortgage?"),
            ('Part Payment', "Can I make part payments towards the mortgage?"),
            ('Maximum Loan Amount', "What is the maximum loan amount I can borrow?"),
            ('Loan Tracking', "How can I track the status of my mortgage?"),
            ('Automatic Deduction', "Is automatic deduction available for mortgage payments?"),
            ('Balance Transfer', "How does a balance transfer work for a mortgage?"),
            ('Self-Help Groups (SHGs)', "What are Self-Help Groups (SHGs) and how do they relate to loans?"),
            ('Joint Liability Groups (JLGs)', "What are Joint Liability Groups (JLGs) and their role in borrowing?"),
            ('Interest Rates', "How do interest rates on microfinance loans compare to traditional loans?"),
        ],
        'gold': [
            ('Loan Sanction Letter', "What details are included in the loan sanction letter?"),
            ('Sanctioned Amount', "What is the sanctioned amount for this loan?"),
            ('Interest Rate', "What is the interest rate for this loan?"),
            ('Tenure', "What is the tenure or duration of the loan?"),
            ('Repayment Schedule', "What does the repayment schedule include?"),
            ('Disbursement Schedule', "What does the disbursement schedule outline?"),
            ('Gold Purity', "What is the required gold purity for the loan?"),
            ('Gold Weight', "What is the weight of the gold needed for the loan?"),
            ('Valuation', "How is the value of the gold assessed?"),
            ('Loan-to-Value (LTV) Ratio', "What is the Loan-to-Value (LTV) ratio for this gold loan?"),
            ('Pawnbroker', "Who is a pawnbroker, and what is their role in gold loans?"),
            ('Pawn Ticket', "What is a pawn ticket and what does it signify?"),
            ('Credit Score', "How does my credit score affect a gold loan application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for a gold loan?"),
            ('Required Documents', "What documents are required for a gold loan application?"),
            ('Approval Turnaround', "What is the approval turnaround time for a gold loan?"),
            ('Loan Default', "What happens if I default on the gold loan?"),
            ('Dispute Resolution', "How are disputes resolved for gold loans?"),
            ('Gold Loan Renewal', "What is involved in renewing a gold loan?"),
            ('Gold Loan Foreclosure', "What occurs in case of gold loan foreclosure?"),
            ('Gold Loan Interest Rates', "How do interest rates for gold loans compare to other unsecured loans?"),
            ('Processing Fees', "What processing fees are associated with a gold loan?"),
            ('Hidden Charges', "Are there any hidden charges for this gold loan?"),
            ('Part Payment', "Can I make a part payment towards the gold loan?"),
            ('Maximum Loan Amount', "What is the maximum loan amount I can get for gold?"),
            ('Loan Tracking', "How can I track the status of my gold loan?"),
            ('Automatic Deduction', "Is automatic deduction available for gold loan payments?"),
            ('Balance Transfer', "How does a balance transfer work for a gold loan?"),
        ],
        'vehicle': [
            ('Loan Sanction Letter', "What details are included in the loan sanction letter?"),
            ('Sanctioned Amount', "What is the sanctioned amount for this loan?"),
            ('Interest Rate', "What is the interest rate for this loan?"),
            ('Tenure', "What is the tenure or duration of the loan?"),
            ('Repayment Schedule', "What does the repayment schedule include?"),
            ('Disbursement Schedule', "What does the disbursement schedule outline?"),
            ('Loan-to-Value (LTV) Ratio', "What is the Loan-to-Value (LTV) ratio for this vehicle loan?"),
            ('Down Payment', "How much down payment is required for the vehicle loan?"),
            ('Vehicle Registration', "What is involved in the vehicle registration process?"),
            ('Insurance', "Is vehicle insurance required for the loan?"),
            ('Hypothecation', "How does hypothecation apply to this vehicle loan?"),
            ('Foreclosure', "What happens in case of foreclosure?"),
            ('Credit Score', "How does my credit score affect my vehicle loan application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for this vehicle loan?"),
            ('Required Documents', "What documents are required for the vehicle loan application?"),
            ('Approval Turnaround', "What is the approval turnaround time for the vehicle loan?"),
            ('Loan Transfer', "Can I transfer my vehicle loan to another lender?"),
            ('Loan Refinancing', "How does vehicle loan refinancing work?"),
            ('Tax Benefits', "Are there any tax benefits associated with this vehicle loan?"),
            ('Loan Default', "What occurs if I default on the vehicle loan?"),
            ('Dispute Resolution', "How are disputes resolved for this loan?"),
            ('Processing Fees', "What processing fees are associated with the vehicle loan application?"),
            ('Hidden Charges', "Are there any hidden charges for this vehicle loan?"),
            ('Part Payment', "Can I make a part payment towards the vehicle loan?"),
            ('Maximum Loan Amount', "What is the maximum loan amount I can get for the vehicle?"),
            ('Loan Tracking', "How can I track the status of my vehicle loan?"),
            ('Automatic Deduction', "Is automatic deduction available for the vehicle loan payments?"),
            ('Balance Transfer', "How does a balance transfer work for this vehicle loan?"),
        ],
        'business': [
            ('Loan Sanction Letter', "What details are included in the loan sanction letter?"),
            ('Sanctioned Amount', "What is the sanctioned amount for this loan?"),
            ('Interest Rate', "What is the interest rate for this loan?"),
            ('Tenure', "What is the tenure of the loan?"),
            ('Repayment Schedule', "What does the repayment schedule consist of?"),
            ('Disbursement Schedule', "What does the disbursement schedule outline?"),
            ('Collateral', "What assets can be used as collateral for a business loan?"),
            ('Guarantor', "What role does a guarantor play in a business loan?"),
            ('Working Capital Loan', "What is a working capital loan and how is it used?"),
            ('Term Loan', "What is a term loan and how does it work?"),
            ('Overdraft Facility', "What is an overdraft facility and how can it benefit my business?"),
            ('Equipment Financing', "How does equipment financing work for purchasing business equipment?"),
            ('Financial Ratios', "What financial ratios are important for assessing my business's financial health?"),
            ('Business Plan', "What should be included in a business plan for a loan application?"),
            ('Credit Score', "How does my credit score affect a business loan application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for a business loan?"),
            ('Required Documents', "What documents are required to apply for a business loan?"),
            ('Approval Turnaround', "How long does it take to get loan approval?"),
            ('Loan Transfer', "What is involved in transferring a business loan to another lender?"),
            ('Loan Refinancing', "How does loan refinancing work for a business?"),
            ('Tax Benefits', "What tax benefits are available for business loans?"),
            ('Loan Default', "What happens if my business defaults on the loan?"),
            ('Dispute Resolution', "How are disputes regarding the loan resolved?"),
            ('Processing Fees', "What are the processing fees for a business loan?"),
            ('Hidden Charges', "Are there any hidden charges associated with this loan?"),
            ('Part Payment', "Can I make a part payment towards the business loan?"),
            ('Maximum Loan Amount', "What is the maximum loan amount available for a business?"),
            ('Loan Tracking', "How can I track the status of my business loan?"),
            ('Automatic Deduction', "Is automatic deduction available for loan payments?"),
            ('Balance Transfer', "How does a balance transfer work for a business loan?"),
        ],
        'credit card': [
            ('Credit Card Loan Agreement', "What details are included in the credit card loan agreement?"),
            ('Sanctioned Amount', "What is the sanctioned amount for the credit card?"),
            ('Interest Rate', "What is the interest rate on the outstanding balance?"),
            ('Repayment Schedule', "What does the repayment schedule entail?"),
            ('Grace Period', "What is the grace period for the credit card?"),
            ('Annual Fee', "Are there any credit cards available with no annual fee?"),
            ('Cash Advance Fee', "What is the cash advance fee and how is it applied?"),
            ('Foreign Transaction Fee', "What is the foreign transaction fee and when is it charged?"),
            ('Late Payment Fee', "How is the late payment fee determined?"),
            ('Overlimit Fee', "What is the overlimit fee and when does it apply?"),
            ('Balance Transfer Fee', "What is the balance transfer fee and how is it calculated?"),
            ('Credit Utilization Ratio', "How is the credit utilization ratio calculated?"),
            ('Reward Points', "What are reward points and how can they be redeemed?"),
            ('Credit Score', "How does my credit score impact my credit card loan application?"),
            ('Eligibility Criteria', "What are the eligibility criteria for a credit card loan?"),
            ('Required Documents', "What documents are required to apply for a credit card loan?"),
            ('Approval Turnaround', "How long does it take to get approval for a credit card loan?"),
            ('Dispute Resolution', "What is the process for resolving disputes related to the credit card loan?"),
            ('Loan Transfer', "Can I transfer my credit card loan to another lender?"),
            ('Loan Refinancing', "How does credit card loan refinancing work?"),
            ('Tax Benefits', "Are there any tax benefits associated with a credit card loan?"),
            ('Loan Default', "What happens if I default on my credit card loan?"),
            ('Dispute Resolution', "How are disputes with credit card companies typically resolved?"),
            ('Processing Fees', "What are the processing fees for a credit card loan?"),
            ('Hidden Charges', "Are there any hidden charges associated with the credit card loan?"),
            ('Part Payment', "Can I make part payments towards the credit card loan?"),
            ('Maximum Loan Amount', "What is the maximum loan amount available on the credit card?"),
            ('Loan Tracking', "How can I track the status of my credit card loan?"),
            ('Automatic Deduction', "Is automatic deduction available for credit card loan payments?"),
            ('Balance Transfer', "How does a balance transfer work for a credit card loan?"),
        ],
    },
    'other': {
        'default': [
            ('Document Type', "What type of document is this?"),
            ('Date of Document', "What is the date of this document?"),
            ('Issuing Authority', "Who is the issuing authority or organization for this document?"),
            ('Purpose', "What is the main purpose of this document?"),
            ('Key Parties', "Who are the key parties involved in this document?"),
            ('Main Subject', "What is the main subject or topic of this document?"),
            ('Key Terms', "What are the key terms and definitions in this document?"),
            ('Important Dates', "Are there any important dates or deadlines mentioned in this document?"),
        ],
    }
}
