FROM python:3.11-slim

WORKDIR /app
COPY requirements-redis.txt .
RUN pip install --no-cache-dir -r requirements-redis.txt

COPY app /app

ENV REDIS_URL=redis://<YOUR_REDIS_IP>:6379/0

CMD ["celery", "-A", "celery_app.celery_app", "worker", "--pool=solo", "--loglevel=info"]

